/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as InteligenciaDeMercadoRouteImport } from './routes/inteligencia-de-mercado'
import { Route as PorQueYucatanRouteImport } from './routes/por-que-yucatan'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDesarrollosRouteImport } from './routes/admin.desarrollos'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminPropiedadesRouteImport } from './routes/admin.propiedades'
import { Route as AdminRecursosRouteImport } from './routes/admin.recursos'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as DesarrollosIndexRouteImport } from './routes/desarrollos.index'
import { Route as DesarrollosIdRouteImport } from './routes/desarrollos.$id'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as PropiedadesIndexRouteImport } from './routes/propiedades.index'
import { Route as PropiedadesIdRouteImport } from './routes/propiedades.$id'
import { Route as RecursosSlugRouteImport } from './routes/recursos.$slug'
import { Route as AdminContenidoModuloRouteImport } from './routes/admin.contenido.$modulo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaDeMercadoRoute = InteligenciaDeMercadoRouteImport.update({
  id: '/inteligencia-de-mercado',
  path: '/inteligencia-de-mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const PorQueYucatanRoute = PorQueYucatanRouteImport.update({
  id: '/por-que-yucatan',
  path: '/por-que-yucatan',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesarrollosRoute = AdminDesarrollosRouteImport.update({
  id: '/desarrollos',
  path: '/desarrollos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropiedadesRoute = AdminPropiedadesRouteImport.update({
  id: '/propiedades',
  path: '/propiedades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecursosRoute = AdminRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const DesarrollosIndexRoute = DesarrollosIndexRouteImport.update({
  id: '/desarrollos/',
  path: '/desarrollos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesarrollosIdRoute = DesarrollosIdRouteImport.update({
  id: '/desarrollos/$id',
  path: '/desarrollos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIndexRoute = PropiedadesIndexRouteImport.update({
  id: '/propiedades/',
  path: '/propiedades/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIdRoute = PropiedadesIdRouteImport.update({
  id: '/propiedades/$id',
  path: '/propiedades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosSlugRoute = RecursosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RecursosRoute,
} as any)
const AdminContenidoModuloRoute = AdminContenidoModuloRouteImport.update({
  id: '/contenido/$modulo',
  path: '/contenido/$modulo',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/empresa': typeof EmpresaRoute
  '/inteligencia-de-mercado': typeof InteligenciaDeMercadoRoute
  '/por-que-yucatan': typeof PorQueYucatanRoute
  '/recursos': typeof RecursosRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/desarrollos': typeof AdminDesarrollosRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/propiedades': typeof AdminPropiedadesRoute
  '/admin/recursos': typeof AdminRecursosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/desarrollos/$id': typeof DesarrollosIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/recursos/$slug': typeof RecursosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/desarrollos/': typeof DesarrollosIndexRoute
  '/propiedades/': typeof PropiedadesIndexRoute
  '/admin/contenido/$modulo': typeof AdminContenidoModuloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/empresa': typeof EmpresaRoute
  '/inteligencia-de-mercado': typeof InteligenciaDeMercadoRoute
  '/por-que-yucatan': typeof PorQueYucatanRoute
  '/recursos': typeof RecursosRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/desarrollos': typeof AdminDesarrollosRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/propiedades': typeof AdminPropiedadesRoute
  '/admin/recursos': typeof AdminRecursosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/desarrollos/$id': typeof DesarrollosIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/recursos/$slug': typeof RecursosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/desarrollos': typeof DesarrollosIndexRoute
  '/propiedades': typeof PropiedadesIndexRoute
  '/admin/contenido/$modulo': typeof AdminContenidoModuloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/empresa': typeof EmpresaRoute
  '/inteligencia-de-mercado': typeof InteligenciaDeMercadoRoute
  '/por-que-yucatan': typeof PorQueYucatanRoute
  '/recursos': typeof RecursosRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/desarrollos': typeof AdminDesarrollosRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/propiedades': typeof AdminPropiedadesRoute
  '/admin/recursos': typeof AdminRecursosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/desarrollos/$id': typeof DesarrollosIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/recursos/$slug': typeof RecursosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/desarrollos/': typeof DesarrollosIndexRoute
  '/propiedades/': typeof PropiedadesIndexRoute
  '/admin/contenido/$modulo': typeof AdminContenidoModuloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contacto'
    | '/empresa'
    | '/inteligencia-de-mercado'
    | '/por-que-yucatan'
    | '/recursos'
    | '/reset-password'
    | '/admin/desarrollos'
    | '/admin/newsletter'
    | '/admin/propiedades'
    | '/admin/recursos'
    | '/admin/usuarios'
    | '/desarrollos/$id'
    | '/legal/$slug'
    | '/propiedades/$id'
    | '/recursos/$slug'
    | '/admin/'
    | '/desarrollos/'
    | '/propiedades/'
    | '/admin/contenido/$modulo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/empresa'
    | '/inteligencia-de-mercado'
    | '/por-que-yucatan'
    | '/recursos'
    | '/reset-password'
    | '/admin/desarrollos'
    | '/admin/newsletter'
    | '/admin/propiedades'
    | '/admin/recursos'
    | '/admin/usuarios'
    | '/desarrollos/$id'
    | '/legal/$slug'
    | '/propiedades/$id'
    | '/recursos/$slug'
    | '/admin'
    | '/desarrollos'
    | '/propiedades'
    | '/admin/contenido/$modulo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contacto'
    | '/empresa'
    | '/inteligencia-de-mercado'
    | '/por-que-yucatan'
    | '/recursos'
    | '/reset-password'
    | '/admin/desarrollos'
    | '/admin/newsletter'
    | '/admin/propiedades'
    | '/admin/recursos'
    | '/admin/usuarios'
    | '/desarrollos/$id'
    | '/legal/$slug'
    | '/propiedades/$id'
    | '/recursos/$slug'
    | '/admin/'
    | '/desarrollos/'
    | '/propiedades/'
    | '/admin/contenido/$modulo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  EmpresaRoute: typeof EmpresaRoute
  InteligenciaDeMercadoRoute: typeof InteligenciaDeMercadoRoute
  PorQueYucatanRoute: typeof PorQueYucatanRoute
  RecursosRoute: typeof RecursosRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  DesarrollosIdRoute: typeof DesarrollosIdRoute
  LegalSlugRoute: typeof LegalSlugRoute
  PropiedadesIdRoute: typeof PropiedadesIdRoute
  DesarrollosIndexRoute: typeof DesarrollosIndexRoute
  PropiedadesIndexRoute: typeof PropiedadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia-de-mercado': {
      id: '/inteligencia-de-mercado'
      path: '/inteligencia-de-mercado'
      fullPath: '/inteligencia-de-mercado'
      preLoaderRoute: typeof InteligenciaDeMercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/por-que-yucatan': {
      id: '/por-que-yucatan'
      path: '/por-que-yucatan'
      fullPath: '/por-que-yucatan'
      preLoaderRoute: typeof PorQueYucatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/desarrollos': {
      id: '/admin/desarrollos'
      path: '/desarrollos'
      fullPath: '/admin/desarrollos'
      preLoaderRoute: typeof AdminDesarrollosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/propiedades': {
      id: '/admin/propiedades'
      path: '/propiedades'
      fullPath: '/admin/propiedades'
      preLoaderRoute: typeof AdminPropiedadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recursos': {
      id: '/admin/recursos'
      path: '/recursos'
      fullPath: '/admin/recursos'
      preLoaderRoute: typeof AdminRecursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/desarrollos/': {
      id: '/desarrollos/'
      path: '/desarrollos'
      fullPath: '/desarrollos/'
      preLoaderRoute: typeof DesarrollosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desarrollos/$id': {
      id: '/desarrollos/$id'
      path: '/desarrollos/$id'
      fullPath: '/desarrollos/$id'
      preLoaderRoute: typeof DesarrollosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/': {
      id: '/propiedades/'
      path: '/propiedades'
      fullPath: '/propiedades/'
      preLoaderRoute: typeof PropiedadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/$id': {
      id: '/propiedades/$id'
      path: '/propiedades/$id'
      fullPath: '/propiedades/$id'
      preLoaderRoute: typeof PropiedadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/$slug': {
      id: '/recursos/$slug'
      path: '/$slug'
      fullPath: '/recursos/$slug'
      preLoaderRoute: typeof RecursosSlugRouteImport
      parentRoute: typeof RecursosRoute
    }
    '/admin/contenido/$modulo': {
      id: '/admin/contenido/$modulo'
      path: '/contenido/$modulo'
      fullPath: '/admin/contenido/$modulo'
      preLoaderRoute: typeof AdminContenidoModuloRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDesarrollosRoute: typeof AdminDesarrollosRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminPropiedadesRoute: typeof AdminPropiedadesRoute
  AdminRecursosRoute: typeof AdminRecursosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContenidoModuloRoute: typeof AdminContenidoModuloRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDesarrollosRoute: AdminDesarrollosRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminPropiedadesRoute: AdminPropiedadesRoute,
  AdminRecursosRoute: AdminRecursosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContenidoModuloRoute: AdminContenidoModuloRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RecursosRouteChildren {
  RecursosSlugRoute: typeof RecursosSlugRoute
}

const RecursosRouteChildren: RecursosRouteChildren = {
  RecursosSlugRoute: RecursosSlugRoute,
}

const RecursosRouteWithChildren = RecursosRoute._addFileChildren(
  RecursosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactoRoute: ContactoRoute,
  EmpresaRoute: EmpresaRoute,
  InteligenciaDeMercadoRoute: InteligenciaDeMercadoRoute,
  PorQueYucatanRoute: PorQueYucatanRoute,
  RecursosRoute: RecursosRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  DesarrollosIdRoute: DesarrollosIdRoute,
  LegalSlugRoute: LegalSlugRoute,
  PropiedadesIdRoute: PropiedadesIdRoute,
  DesarrollosIndexRoute: DesarrollosIndexRoute,
  PropiedadesIndexRoute: PropiedadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
